---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dsop-api
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /dsop-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /dsop-api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    rules:
      - application: personopplysninger-proxy
        namespace: personbruker
        cluster: {{ fss-cluster }}
    outbound:
      external:
        - host: {{ personopplysninger-host }}
  resources:
    limits:
      cpu: '3'
      memory: 1500Mi
    requests:
      memory: 1500Mi
  envFrom:
    - secret: dsop-api-secret
    - configmap: loginservice-idporten
  prometheus:
    enabled: true
    path: /dsop-api/internal/prometheus
