apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dsop-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /person/dsop-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/dsop-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/dsop-api/internal/metrics
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  webproxy: true
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ sporingslogg-host }}
        - host: {{ kodeverk-api-host }}
        - host: {{ ereg-host }}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: dsop-api-secret
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
