apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dsop-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/dsop-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/dsop-api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    rules:
      - application: {{ sporingslogg-name }}
        namespace: pensjonsamhandling
        cluster: {{ fss-cluster }}
    outbound:
      external:
        - host: {{ sporingslogg-host }}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
         {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: dsop-api-secret
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
